---
- name: Provision AI tools on server
  hosts: localhost

  tasks:
  - name: Create a log directory
    ansible.builtin.file:
      path: /home/ubuntu/logs
      state: directory

  - name: Add APT Repository for Python
    ansible.builtin.shell: add-apt-repository ppa:deadsnakes/ppa

  - name: Update APT
    ansible.builtin.shell: apt update

  - name: Install Python 3.12
    become: true
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - python3.12
    - python3.12-venv

  - name: Install pip for Python 3.12
    ansible.builtin.shell: "python3.12 -m ensurepip --upgrade"

  - name: Get Python 3.12 Pythonpath
    shell: "which python3.12"
    register: python_path
    changed_when: false

  - name: Create Python Virtual Environment
    shell: "{{ python_path.stdout }} -m venv /home/ubuntu/ai-venv"
    args:
      creates: "/home/ubuntu/ai-venv"

  - name: Install packages
    apt:
      pkg:
      - unzip
      - docker.io
  
  - name: Adding Python packages via pip
    pip:
      executable: "/home/ubuntu/ai-venv/bin/pip"
      name:
      - jupyterlab
      - notebook
      - ollama

  - name: Install Ollama
    ansible.builtin.shell: curl -fsSL https://ollama.com/install.sh | sh

  - name: Pull LLama 3.2 Model
    ansible.builtin.shell: ollama pull llama3.2

  - name: Pull Gemma2:27b Model
    ansible.builtin.shell: ollama pull gemma2:27b

  - name: Generate the notebook configuration
    shell: "/home/ubuntu/ai-venv/bin/jupyter notebook --generate-config -y"

  - name: Add password to Jupyter configuration
    expect:
      command: "/home/ubuntu/ai-venv/bin/jupyter notebook password"
      responses:
        Enter password: "{{ pw }}"
        Verify password: "{{ pw }}"

  - name: Create Jupyter content folder
    ansible.builtin.shell: mkdir /home/ubuntu/jupyter

  - name: Copy Jupyter examples into content folder
    ansible.builtin.shell: cp -a /home/ubuntu/ai-installation/code_samples/. /home/ubuntu/jupyter/

  - name: Download EasyDiffusion installer
    ansible.builtin.shell: wget https://github.com/cmdr2/stable-diffusion-ui/releases/latest/download/Easy-Diffusion-Linux.zip -O /home/ubuntu/easy-diffusion.zip

  - name: Unzip EasyDiffusion installer
    ansible.builtin.shell: unzip /home/ubuntu/easy-diffusion.zip -d /home/ubuntu/

  - name: Clean up EasyDiffusion installer ZIP
    ansible.builtin.shell: rm /home/ubuntu/easy-diffusion.zip

  - name: Start Jupyter Server
    shell: "/home/ubuntu/ai-venv/bin/jupyter lab --ServerApp.root_dir=/home/ubuntu/jupyter --no-browser --port=8090 --ip=0.0.0.0 --allow-root > /home/ubuntu/logs/jupyter.log 2>&1 &"
    async: 2

  - name: Start Open WebUI Server
    shell: "sudo docker run -d --network=host -e OLLAMA_BASE_URLS=http://127.0.0.1:11434 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main"

  #- name: Create Open WebUI User
  #  shell: "curl -X POST http://127.0.0.1:3000/api/v1/auths/signup -d '{\"name\":\"AI@Cisco\",\"email\":\"ai@cisco.com\",\"password\":\"{{ pw }}\",\"profile_image_url\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAXNSR0IArs4c6QAABUdJREFUeF7tnFtsFFUcxr+Zve9sGigUo4ESL2AVBBKq4gVDoqLhAURBtK2mRBNDfNBo9MFEHtCYmPggJjyYeCvFotUKD96NIgoYhahIQmnLJSoVUNSKO7vd3dkdM33Y7rFtaHam02+S/7x1duecb36/ftszM221f1+ptSEbDQFNhNC4GAoiQrh8iBAyHyJEhLARIMsjP0NECBkBsjjSEBFCRoAsjjREhJARIIsjDREhZATI4khDRAgZAbI40hARQkaALI40RISQESCLIw0RIWQEyOJIQ0QIGQGyONIQEUJGgCyONESEkBEgiyMNESFkBMjiSENECBkBsjjSEBHiIYFQDKG6RmVA20qjdPagh5P4O1SgGxJtfBrRhY+OIGZumwM795e/JD2aLdBCjKZuaIkZI1AUDm1B7ruNHiHyd5jACtFr5yG5+qtRadnZP2B2NPhL0qPZAiskfks7wrNXjIkh03U9SgM9HmHyb5jACkm1/gaEYmOSso7vwOCuB/0j6dFMgRQSvnQN4steVhFYWSCcKO+zrQzMtlkeYfJvmEAKSa7eDb12/jB8sx/Wr58h0tCqkMt+cjeKJz/3j6YHMwVOiBatgXHfcecvusunn//+eVh9byG57gcFSfH0XmQ/WOkBJv+GCJyQ6NUbEV3wSAUhG+bW2bALJox7D0NLXjD8WslC+o2LALvoH1GXMwVOiNHUAy0xvXzapT8PIbNz2dDXsWufRWT+BgVJ7psnUTj8qktM/h0eKCH6tAVI3rFLoTO4ewOso51D+7REHYymI8rrpYFeZLqu84+oy5kCJSR+65sI199e8ZGUR/r1CxUExrofoaUqV1c2zG2Xwc4NuETlz+GBEpJafwrQo2UyzgrKWUlVbtHFTyG66HFlX/6nzcjv3+QPUZezBEZIeM49iN+0RTnd7PsrUDzzrbJPi02B0XJM2Wdnf4fZcYVLVP4cHhghyTu/hj71yjIVO/8PzPZLRqWUXLsfeo36WqZrCUoDff5QdTFLIIRosVoYLb3KtUehpx25PSNvvTssnFvyzq35ys069i4Gv3zIBSp/Dg2EkNg1mxC56mGFiHN73c6cHpWSFkogtnSz+rEVkFspgRBiNPdCi09z/S2a/XgNiv3qstn1oB4PQC9En74IyVXe3I8qntqD7IerPEbo7XD0QuLLtyM8a7k3Zx2AWyncQjQdqdZ+5drDzp6F9ctH4xIUmtEIfaq63M3tfQyFI23jOn4y3kQtJDK3GbGlL6k/zPc9gUL3a+NipU+5HMm79invLf3djcx7N47r+Ml4E7UQB6YDtbxV8ZFjtPTBWTYPb/bQ9YudPzcZvM87J60QZ1VlNDvPxIefe1TzfMNZ/kbmtigg8gdfRP7AM+eFMxlvoBUSW/IcIvPUC7lqngDqNRcjufaAek2SOQNz+/BV/2SAH2tOWiEjPmqsLNJtM6ti9/9nKM4gmXcaUTp3oqrxJvIgSiGhusVIrPxUOW/rxE4MfvFAVSxiN7yASMN6dbyjnXCepbBtlEISt3UiNPNmhZWb37PSU/Ujnrc7j3zNrfVsPjj/s7Vx/8/QIqkyLOfaw+yoWG1VgXG0Xzs1314IO32yitEm7hDKhkzc6fKPLELIHIkQEUJGgCyONESEkBEgiyMNESFkBMjiSENECBkBsjjSEBFCRoAsjjREhJARIIsjDREhZATI4khDRAgZAbI40hARQkaALI40RISQESCLIw0RIWQEyOJIQ0QIGQGyONIQEUJGgCyONESEkBEgiyMNESFkBMjiSENECBkBsjjSEBFCRoAsjjSETMh/FHs5A+2/FucAAAAASUVORK5CYII=\"}'"

  - name: Start EasyDiffusion Web UI
    shell: "/home/ubuntu/easy-diffusion/start.sh"
